### ISSUE TITLE
New item: Europe needs strong software!

### ISSUE THREAD

**Issue by tvdstorm** [versen/versen.github.io#27]
Software engineering research is crucial for a strong and independent Europe. A small group of software researchers from France, Finland, and the Netherlands, have written a one-page document as a call to action for increased funding of software engineering research in Europe. This document can be found here:

https://drive.google.com/file/d/1Pn4HINXQI2SSsyF051xOzxfEjxzGeEoW/view?usp=sharing

The one-pager is the basis for an online petition to make a strong statement backed by organizations and software researchers in Europe and elsewhere, to signal to policy-makers (both national and European-level) the urgency of increased funding for software research:

https://www.ipetitions.com/petition/europe-needs-strong-software-research

If you want to endorse the message for a strong Europe, with strong software engineering research, sign the petition!
And distribute among colleagues, heads of departments, policy makers, etc. Don't hesitate to share on social media using the hashtags #EuropeNeedsSoftwareResearch #FundSofwareResearchEU.

The document and petition is an effort by Paris Avgeriou, Marieke Huisman, Jean-Marc Jezequel, Tomi Männistö, Tommi Mikonen, Romain Rouvoy, Alexander Serebrenik, Kari Smolander, Tijs van der Storm, on behalf of the national software engineering associations VERSEN (https://www.versen.nl), GDR GPL (https://gdr-gpl.cnrs.fr/), and TIVIA (https://tivia.fi/in-english/).

**Comment by mauricioaniche** [comment]
Done, @tvdstorm: https://www.versen.nl/news_items/europe-needs-strong-software/

Next time, feel also free to submit a PR directly!
