### ISSUE TITLE
Update honorary members page with 2021 fellows

### ISSUE THREAD

**Issue by tvdstorm** [versen/versen.github.io#40]
The current  page of honorary members section only shows the 2020 fellows. See: https://www.versen.nl/contents/honorary-members. 

The page needs to be updated for 2021, with Peter van Emde Boas and Wim Hesselink as 2021 fellows. 

(Please contact me directly for the videos, to be uploaded to youtube.)

**Comment by feitosa-daniel** [comment]
Solved with commit "[Add 2021 honorary fellows](https://github.com/versen/versen.github.io/commit/09a36bf5827675cb4286b0ac1b5771941e1c7192)".
