### ISSUE TITLE
regenerate members list

### ISSUE THREAD

**Issue by jurgenvinju** [versen/versen.github.io#48]
Christel van Dam has cleaned up all affiliation data of the members (typo's, inconsistencies) without changing the actual data. So it's time to extract the list again from mailchimp.

**Comment by feitosa-daniel** [comment]
Sure thing! Have a look at my message on Slack regarding the admin. 👀 😃

**Comment by jurgenvinju** [comment]
Ok I regenerated but something went wrong and the page is gone.. It's still in the source though so I'll look again tomorrow what went wrong.

**Comment by feitosa-daniel** [comment]
I saw you found the issue (a typo in the template)! The page is online. I'm closing the issue for now.
